package com.airtribe.meditrack.enums;

public enum Specialist {
    CARDIOLOGIST,
    DERMATOLOGIST,
    NEUROLOGIST,
    PEDIATRICIAN,
    ORTHOPEDIC,
    GYNECOLOGIST,
    PSYCHIATRIST,
    ENDOCRINOLOGIST,
    ONCOLOGIST,
    GASTROENTEROLOGIST,
    PULMONOLOGIST,
    RHEUMATOLOGIST,
    UROLOGIST,
    HEMATOLOGIST,
    INFECTIOUS_DISEASE_SPECIALIST,
    ALLERGIST,
    IMMUNOLOGIST,
    NEPHROLOGIST,
    OTOLARYNGOLOGIST,
    OPHTHALMOLOGIST,
    DENTIST,
    GENERAL_PRACTITIONER,
    GENERAL_PHYSICIAN
}
